### PR TITLE
Support for Speech/LUIS containers

### PR DESCRIPTION
**Pull request by tomconte**
Sharing this fix for #15 to share progress and solicit feedback.

TODO:

- [x] Get the LUIS endpoint from the configuration (we need two endpoints, one for Speech and one for LUIS) 
- [x] The intent does not appear in the ROS topic, maybe the JSON format is different from the one received from the Speech SDK ➡️ switched to the v2 LUIS endpoint which returns the expected JSON format.
- [x] Review the code that determines whether to use web services or containers

### CODE REVIEW

**Comment by tomconte** [comment]
I think this PR is now ready for review. /cc @ooeygui

**Comment by ooeygui** [comment]
The change looks good, thank you! Can you confirm you have built and tested on Windows and Linux? (Our CI was offline; I had to reenable it)

**Comment by tomconte** [comment]
Actually, I have not tested on Windows yet... I will deploy a VM to give it a try!

**Comment by tomconte** [comment]
Status update: I am still trying to run the node (just master, not my PR) on Windows.

I managed to build by using `add_compile_options(/std:c++17)` in `CMakeLists.txt`. 

Now I get an error when launching the node:

```
auto-starting new master
process[master]: started with pid [5176]
ROS_MASTER_URI=http://127.0.0.1:11311
setting /run_id to 4766104d-1540-11ec-90c2-6045bd884985
process[rosout-1]: started with pid [1556]
started core service [/rosout]
process[luis_test-2]: started with pid [6724]
←[31m[luis_test-2] process has died [pid 6724, exit code 3221226505, cmd C:\Users\azureuser\luis_ws\devel\lib\ros_msft_luis\ros_msft_luis_node.exe __name:=luis_test __log:=C:\Users\azureuser\.ros\log\4766104d-1540-11ec-90c2-6045bd884985\luis_test-2.log].
log file: C:\Users\azureuser\.ros\log\4766104d-1540-11ec-90c2-6045bd884985\luis_test-2*.log←[0m
^C
```

Unfortunately the log file does not exist. Will keep investigating.

**Comment by ooeygui** [comment]
We maintain the VSCode ROS extension (http://aka.ms/ros/vscode). After installing, start vscode from your workspace holding LUIS. You can then add a ROS launch configuration, loading the LUIS launch file. And launch debug it.

**Comment by tomconte** [comment]
OK, I got the original node to run, my launch file was messed up... Now going to try and build that PR :-)

**Comment by tomconte** [comment]
It looks we don't have the curl library on Windows:

```
LINK : fatal error LNK1104: cannot open file 'curl.lib'
```

I thought it would be there, as it is a dependency of `resource_retriever` that I am using to make the REST HTTP call.

Any suggestions welcome!

**Comment by ooeygui** [comment]
Libcurl is in the distribution. However, cmake being what it is requires it to be explicitly discovered and included.

```cmake
include(FindCURL)/
if(NOT CURL_FOUND)
  message("CURL not found!  Aborting...")
  fail()
endif(NOT CURL_FOUND)

if (TARGET CURL::libcurl)
  set(CURL_SHIM_LIBRARIES CURL::libcurl)
else()
  set(CURL_SHIM_LIBRARIES ${CURL_LIBRARIES})
endif()

target_link_libraries (${PROJECT_NAME}
...
  ${CURL_SHIM_LIBRARIES}
)
```

You'll also want to put curl in the package.xml:
```xml
  <depend>curl</depend>
```

**Comment by tomconte** [comment]
Thanks for your help! I got it to build and run on Windows. Now I need to go back to Linux and make sure the cmake stanzas for curl still work there :-) Will keep you posted, probably tomorrow as it is EOD here.

**Comment by ooeygui** [comment]
Thank you for working on this :-)

**Comment by tomconte** [comment]
Just pushed the changes to the cmake config for libcurl. This is now built and tested on both Linux and Windows.

**Comment by meguittet** [comment]
@ooeygui do you have an idea when you could approve and merge this PR please? Thank you

**Pull request merged**
